import type { Question } from './questions';

export const pack: Question[] = [
  // ── ARITMETIKA ──────────────────────────────────────────────────────────────
  {
    id: 'pm1-1',
    subject: 'matematika',
    topic: 'Aritmetika – sčítanie',
    prompt: 'Vypočítaj: 4 756 + 2 389',
    type: 'text',
    answer: '7145',
    acceptable: ['7 145'],
    explanation: '4 756 + 2 389 = 7 145.',
  },
  {
    id: 'pm1-2',
    subject: 'matematika',
    topic: 'Aritmetika – odčítanie',
    prompt: 'Vypočítaj: 10 000 − 3 847',
    type: 'text',
    answer: '6153',
    acceptable: ['6 153'],
    explanation: '10 000 − 3 847 = 6 153.',
  },
  {
    id: 'pm1-3',
    subject: 'matematika',
    topic: 'Násobenie',
    prompt: 'Vypočítaj: 36 · 25',
    type: 'text',
    answer: '900',
    explanation: '36 · 25 = 36 · 100 : 4 = 3600 : 4 = 900.',
  },
  {
    id: 'pm1-4',
    subject: 'matematika',
    topic: 'Delenie',
    prompt: 'Vypočítaj: 756 : 9',
    type: 'text',
    answer: '84',
    explanation: '9 · 84 = 756, teda 756 : 9 = 84.',
  },
  {
    id: 'pm1-5',
    subject: 'matematika',
    topic: 'Delenie so zvyškom',
    prompt: 'Koľko je 97 : 7? Napíš výsledok v tvare „podiel zvyšok x" (napr. 13 zvyšok 5).',
    type: 'text',
    answer: '13 zvyšok 6',
    acceptable: ['13 zv 6', '13 zv. 6', '13 zvysok 6'],
    explanation: '7 · 13 = 91, 97 − 91 = 6. Teda 13 zvyšok 6.',
  },
  {
    id: 'pm1-6',
    subject: 'matematika',
    topic: 'Násobenie veľkých čísel',
    prompt: 'Vypočítaj: 47 · 12',
    type: 'text',
    answer: '564',
    explanation: '47 · 12 = 47 · 10 + 47 · 2 = 470 + 94 = 564.',
  },

  // ── SLOVNÉ ÚLOHY ─────────────────────────────────────────────────────────────
  {
    id: 'pm1-7',
    subject: 'matematika',
    topic: 'Slovná úloha – nákup',
    prompt:
      'Čokoláda stojí 1,40 € a džús 0,90 €. Zuzka kúpila 3 čokolády a 2 džúsy. Koľko zaplatila?',
    type: 'text',
    answer: '6',
    acceptable: ['6,00', '6,00 €', '6 €', '6.00'],
    explanation: '3 · 1,40 = 4,20 €; 2 · 0,90 = 1,80 €; spolu 4,20 + 1,80 = 6,00 €.',
  },
  {
    id: 'pm1-8',
    subject: 'matematika',
    topic: 'Slovná úloha – nákup',
    prompt:
      'Kniha stojí 8,50 €. Kamarátka zaplatila 20 € a dostala zvyšok. Koľko € dostala späť?',
    type: 'text',
    answer: '11,50',
    acceptable: ['11.50', '11,50 €', '11.50 €'],
    explanation: '20 − 8,50 = 11,50 €.',
  },
  {
    id: 'pm1-9',
    subject: 'matematika',
    topic: 'Slovná úloha – vek',
    prompt:
      'Starý otec má 66 rokov, vnučka má 11 rokov. Koľkokrát je starý otec starší ako vnučka?',
    type: 'text',
    answer: '6',
    explanation: '66 : 11 = 6. Starý otec je 6-krát starší.',
  },
  {
    id: 'pm1-10',
    subject: 'matematika',
    topic: 'Slovná úloha – vek',
    prompt:
      'Brat je o 5 rokov starší ako sestra. Spolu majú 27 rokov. Koľko rokov má sestra?',
    type: 'text',
    answer: '11',
    explanation: 's + (s + 5) = 27 → 2s = 22 → s = 11 rokov.',
  },
  {
    id: 'pm1-11',
    subject: 'matematika',
    topic: 'Slovná úloha – zdieľanie',
    prompt:
      'Trieda 28 žiakov ide na výlet. Do každého autobusu sa zmestí 12 žiakov. Koľko autobusov potrebujú?',
    type: 'text',
    answer: '3',
    explanation:
      '28 : 12 = 2 zvyšok 4. Dvomi autobusmi by nestačilo, potrebujú teda 3 autobusy.',
  },
  {
    id: 'pm1-12',
    subject: 'matematika',
    topic: 'Slovná úloha – vzdial./rýchl./čas',
    prompt:
      'Auto ide rýchlosťou 80 km/h. Za koľko hodín prejde 360 km? Napíš číslo.',
    type: 'text',
    answer: '4,5',
    acceptable: ['4.5', '4 a pol', '4 hodiny 30 minút', '4 h 30 min'],
    explanation: '360 : 80 = 4,5 hodiny (4 hodiny 30 minút).',
  },
  {
    id: 'pm1-13',
    subject: 'matematika',
    topic: 'Slovná úloha – vzdial./rýchl./čas',
    prompt:
      'Vlak ide 3 hodiny rýchlosťou 120 km/h. Koľko kilometrov prejde?',
    type: 'text',
    answer: '360',
    explanation: '120 · 3 = 360 km.',
  },
  {
    id: 'pm1-14',
    subject: 'matematika',
    topic: 'Slovná úloha – zdieľanie',
    prompt:
      'Pekár upiekol 144 rožkov. Uložil ich do košov po 12 kusov. Koľko košov naplnil?',
    type: 'text',
    answer: '12',
    explanation: '144 : 12 = 12 košov.',
  },
  {
    id: 'pm1-15',
    subject: 'matematika',
    topic: 'Slovná úloha – peniaze',
    prompt:
      'Jano šetril 2 týždne a každý týždeň odložil 7,50 €. Potom minul 6 €. Koľko mu zostalo?',
    type: 'text',
    answer: '9',
    acceptable: ['9,00', '9 €', '9.00'],
    explanation: '2 · 7,50 = 15 €; 15 − 6 = 9 €.',
  },

  // ── ZLOMKY ────────────────────────────────────────────────────────────────────
  {
    id: 'pm1-16',
    subject: 'matematika',
    topic: 'Zlomky',
    prompt: 'Koľko je 1/3 z 270?',
    type: 'text',
    answer: '90',
    explanation: '270 : 3 = 90.',
  },
  {
    id: 'pm1-17',
    subject: 'matematika',
    topic: 'Zlomky',
    prompt: 'Koľko je 2/5 zo 150?',
    type: 'text',
    answer: '60',
    explanation: '150 : 5 = 30; 30 · 2 = 60.',
  },
  {
    id: 'pm1-18',
    subject: 'matematika',
    topic: 'Zlomky',
    prompt: 'Koľko je 3/4 z 96?',
    type: 'text',
    answer: '72',
    explanation: '96 : 4 = 24; 24 · 3 = 72.',
  },
  {
    id: 'pm1-19',
    subject: 'matematika',
    topic: 'Zlomky – slovná úloha',
    prompt:
      'V záhrade je 60 kvetov. Štvrtina sú ruže, zvyšok sú tulipány. Koľko je tulipánov?',
    type: 'text',
    answer: '45',
    explanation: '1/4 z 60 = 15 ruží; 60 − 15 = 45 tulipánov.',
  },
  {
    id: 'pm1-20',
    subject: 'matematika',
    topic: 'Zlomky – porovnanie',
    prompt: 'Ktorý zlomok je väčší?',
    type: 'choice',
    choices: [
      { id: 'a', text: '1/2' },
      { id: 'b', text: '2/5' },
      { id: 'c', text: 'Sú rovnaké' },
      { id: 'd', text: 'Nedá sa porovnať' },
    ],
    answer: 'a',
    explanation: '1/2 = 5/10, 2/5 = 4/10. Teda 1/2 > 2/5.',
  },

  // ── DESATINNÉ ČÍSLA ─────────────────────────────────────────────────────────
  {
    id: 'pm1-21',
    subject: 'matematika',
    topic: 'Desatinné čísla – sčítanie',
    prompt: 'Vypočítaj: 7,8 + 4,35',
    type: 'text',
    answer: '12,15',
    acceptable: ['12.15'],
    explanation: '7,80 + 4,35 = 12,15.',
  },
  {
    id: 'pm1-22',
    subject: 'matematika',
    topic: 'Desatinné čísla – odčítanie',
    prompt: 'Vypočítaj: 15 − 6,4',
    type: 'text',
    answer: '8,6',
    acceptable: ['8.6'],
    explanation: '15,0 − 6,4 = 8,6.',
  },
  {
    id: 'pm1-23',
    subject: 'matematika',
    topic: 'Desatinné čísla – násobenie',
    prompt: 'Vypočítaj: 3,6 · 10',
    type: 'text',
    answer: '36',
    explanation: 'Násobenie 10 posunie desatinnú čiarku o jedno miesto doprava: 36.',
  },
  {
    id: 'pm1-24',
    subject: 'matematika',
    topic: 'Desatinné čísla – násobenie',
    prompt: 'Vypočítaj: 0,47 · 100',
    type: 'text',
    answer: '47',
    explanation: 'Násobenie 100 posunie desatinnú čiarku o dve miesta doprava: 47.',
  },
  {
    id: 'pm1-25',
    subject: 'matematika',
    topic: 'Desatinné čísla – porovnanie',
    prompt: 'Usporiadaj od najmenšieho po najväčšie: 1,5 ; 1,05 ; 1,55 ; 0,9',
    type: 'choice',
    choices: [
      { id: 'a', text: '0,9 ; 1,05 ; 1,5 ; 1,55' },
      { id: 'b', text: '0,9 ; 1,5 ; 1,05 ; 1,55' },
      { id: 'c', text: '1,05 ; 0,9 ; 1,5 ; 1,55' },
      { id: 'd', text: '0,9 ; 1,5 ; 1,55 ; 1,05' },
    ],
    answer: 'a',
    explanation:
      '0,90 < 1,05 < 1,50 < 1,55. Správne poradie: 0,9; 1,05; 1,5; 1,55.',
  },

  // ── RÍMSKE ČÍSLICE ────────────────────────────────────────────────────────────
  {
    id: 'pm1-26',
    subject: 'matematika',
    topic: 'Rímske číslice',
    prompt: 'Zapíš číslicu 48 rímskymi číslicami.',
    type: 'text',
    answer: 'XLVIII',
    explanation: '48 = 40 + 8 = XL + VIII = XLVIII.',
  },
  {
    id: 'pm1-27',
    subject: 'matematika',
    topic: 'Rímske číslice',
    prompt: 'Aké arabské číslo zodpovedá rímskemu číslu XCIX?',
    type: 'text',
    answer: '99',
    explanation: 'XCIX = XC + IX = 90 + 9 = 99.',
  },
  {
    id: 'pm1-28',
    subject: 'matematika',
    topic: 'Rímske číslice',
    prompt: 'Zapíš číslicu 476 rímskymi číslicami.',
    type: 'text',
    answer: 'CDLXXVI',
    explanation:
      '476 = 400 + 70 + 6 = CD + LXX + VI = CDLXXVI.',
  },
  {
    id: 'pm1-29',
    subject: 'matematika',
    topic: 'Rímske číslice',
    prompt: 'Ktoré rímske číslo je väčšie: CDXL alebo DXXI?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'CDXL (440)' },
      { id: 'b', text: 'DXXI (521)' },
      { id: 'c', text: 'Sú rovnaké' },
    ],
    answer: 'b',
    explanation: 'CDXL = 400 + 40 = 440; DXXI = 500 + 21 = 521. Teda DXXI > CDXL.',
  },
  {
    id: 'pm1-30',
    subject: 'matematika',
    topic: 'Rímske číslice',
    prompt: 'Aké arabské číslo zodpovedá rímskemu číslu MCMLXXXIV?',
    type: 'text',
    answer: '1984',
    explanation:
      'M = 1000, CM = 900, LXXX = 80, IV = 4. Spolu 1000 + 900 + 80 + 4 = 1984.',
  },

  // ── PORADIE OPERÁCIÍ ─────────────────────────────────────────────────────────
  {
    id: 'pm1-31',
    subject: 'matematika',
    topic: 'Poradie operácií',
    prompt: 'Vypočítaj: 5 + 3 · 8',
    type: 'text',
    answer: '29',
    explanation: 'Najprv násobenie: 3 · 8 = 24, potom sčítanie: 5 + 24 = 29.',
  },
  {
    id: 'pm1-32',
    subject: 'matematika',
    topic: 'Poradie operácií',
    prompt: 'Vypočítaj: (5 + 3) · 8',
    type: 'text',
    answer: '64',
    explanation: 'Zátvorkа najprv: 5 + 3 = 8, potom 8 · 8 = 64.',
  },
  {
    id: 'pm1-33',
    subject: 'matematika',
    topic: 'Poradie operácií',
    prompt: 'Vypočítaj: 100 − 4 · (6 + 9)',
    type: 'text',
    answer: '40',
    explanation: 'Zátvorkа: 6 + 9 = 15; násobenie: 4 · 15 = 60; odčítanie: 100 − 60 = 40.',
  },
  {
    id: 'pm1-34',
    subject: 'matematika',
    topic: 'Poradie operácií',
    prompt: 'Vypočítaj: 72 : (12 − 3) + 7',
    type: 'text',
    answer: '15',
    explanation: 'Zátvorkа: 12 − 3 = 9; delenie: 72 : 9 = 8; sčítanie: 8 + 7 = 15.',
  },
  {
    id: 'pm1-35',
    subject: 'matematika',
    topic: 'Poradie operácií',
    prompt: 'Vypočítaj: 3 · 4 + 2 · 5 − 10 : 2',
    type: 'text',
    answer: '17',
    explanation:
      'Najprv násobenia a delenie: 3·4 = 12, 2·5 = 10, 10:2 = 5. Potom: 12 + 10 − 5 = 17.',
  },

  // ── RÔZNE – ZAOKRÚHĽOVANIE, POSTUPNOSŤ, LOGIKA ─────────────────────────────
  {
    id: 'pm1-36',
    subject: 'matematika',
    topic: 'Zaokrúhľovanie',
    prompt: 'Zaokrúhli číslo 13 748 na tisícky.',
    type: 'text',
    answer: '14000',
    acceptable: ['14 000'],
    explanation: 'Číslica stoviek je 7 (≥ 5) ⇒ zaokrúhľujeme nahor: 14 000.',
  },
  {
    id: 'pm1-37',
    subject: 'matematika',
    topic: 'Postupnosť',
    prompt: 'Aké číslo chýba? 3, 6, 12, 24, ___, 96',
    type: 'text',
    answer: '48',
    explanation: 'Každý člen sa násobí 2: 24 · 2 = 48.',
  },
  {
    id: 'pm1-38',
    subject: 'matematika',
    topic: 'Postupnosť',
    prompt: 'Aké číslo doplníš? 1, 3, 6, 10, 15, ___',
    type: 'text',
    answer: '21',
    explanation:
      'Rozdiely rastú o 1: +2, +3, +4, +5, +6. Teda 15 + 6 = 21.',
  },
  {
    id: 'pm1-39',
    subject: 'matematika',
    topic: 'Slovná úloha – logika',
    prompt:
      'Na poličke stojí 5 červených, 3 modré a 4 zelené knihy. Aká časť (zlomok) všetkých kníh sú modré?',
    type: 'choice',
    choices: [
      { id: 'a', text: '1/4' },
      { id: 'b', text: '3/12' },
      { id: 'c', text: '1/5' },
      { id: 'd', text: '3/10' },
    ],
    answer: 'a',
    explanation:
      'Spolu je 5 + 3 + 4 = 12 kníh. Modré: 3/12 = 1/4. Správna odpoveď je 1/4.',
  },
  {
    id: 'pm1-40',
    subject: 'matematika',
    topic: 'Slovná úloha – kombinatorika',
    prompt:
      'Na raňajky si môžeš vybrať jeden nápoj (čaj alebo kakao) a jeden pečivo (rožok, pagáč alebo croissant). Koľko rôznych kombinácií raňajok máš?',
    type: 'text',
    answer: '6',
    explanation: '2 nápoje · 3 pečivá = 6 kombinácií.',
  },
];
