import type { Question } from './questions';

export const pack: Question[] = [
  // ── LITERATÚRA ──────────────────────────────────────────────────────────────

  {
    id: 'ps2-1',
    subject: 'slovencina',
    topic: 'Literatúra',
    prompt: 'Čo je to rozprávka?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'Príbeh o skutočných historických udalostiach a miestach' },
      { id: 'b', text: 'Prozaický útvar s fantastickými postavami a záporom, v ktorom dobro víťazí nad zlom' },
      { id: 'c', text: 'Krátky veršovaný útvar s ponaučením' },
      { id: 'd', text: 'Správa o udalosti z novín' },
    ],
    answer: 'b',
    explanation: 'Rozprávka je prozaický (nie básnický) žáner s nadprirodzenými bytosťami (víly, draci, čarodejnice), kde dobro vždy zvíťazí nad zlom.',
  },
  {
    id: 'ps2-2',
    subject: 'slovencina',
    topic: 'Literatúra',
    prompt: 'Čím sa líši povesť od rozprávky?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'Povesť je vždy veršovaná, rozprávka nie' },
      { id: 'b', text: 'Povesť sa viaže na skutočné miesto alebo historickú udalosť, rozprávka nie' },
      { id: 'c', text: 'Povesť má vždy šťastný koniec, rozprávka nemá' },
      { id: 'd', text: 'Povesť má ponaučenie na konci, rozprávka nie' },
    ],
    answer: 'b',
    explanation: 'Povesť je naviazaná na konkrétne miesto alebo dejinnú udalosť (napr. Bratislavský hrad, Juraj Jánošík), zatiaľ čo rozprávka sa odohráva v neurčitom „kedysi dávno".',
  },
  {
    id: 'ps2-3',
    subject: 'slovencina',
    topic: 'Literatúra',
    prompt: 'Ktoré tvrdenie o bájke je pravdivé?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'Bájka je dlhý román s množstvom postáv' },
      { id: 'b', text: 'Bájka nemá ponaučenie' },
      { id: 'c', text: 'Bájka je krátky príbeh (často veršovaný) s postavami zvierat, ktorý má mravné ponaučenie' },
      { id: 'd', text: 'Bájka sa vždy odohráva v meste' },
    ],
    answer: 'c',
    explanation: 'Bájka (napr. od Ezopa alebo La Fontaina) má zvieracie postavy, ktoré zastupujú ľudské vlastnosti, a záverom nesie ponaučenie (morálku).',
  },
  {
    id: 'ps2-4',
    subject: 'slovencina',
    topic: 'Literatúra',
    prompt: 'Čo je verš?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'Jedna veta v próze' },
      { id: 'b', text: 'Jeden riadok básne' },
      { id: 'c', text: 'Skupina riadkov básne oddelená prázdnym riadkom' },
      { id: 'd', text: 'Zvuková zhoda na konci riadkov' },
    ],
    answer: 'b',
    explanation: 'Verš je jeden riadok básne. Skupina veršov oddelená od ďalšej skupiny sa nazýva sloha (strofa).',
  },
  {
    id: 'ps2-5',
    subject: 'slovencina',
    topic: 'Literatúra',
    prompt: 'Ako sa nazýva skupina veršov oddelená od ostatných prázdnym riadkom?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'rým' },
      { id: 'b', text: 'rytmus' },
      { id: 'c', text: 'sloha (strofa)' },
      { id: 'd', text: 'próza' },
    ],
    answer: 'c',
    explanation: 'Sloha (strofa) je skupina veršov patriacich k sebe, oddelená od nasledujúcej skupiny prázdnym riadkom.',
  },
  {
    id: 'ps2-6',
    subject: 'slovencina',
    topic: 'Literatúra',
    prompt: 'Čo je to prirovnanie? Vyber príklad, ktorý ho dobre ilustruje.',
    type: 'choice',
    choices: [
      { id: 'a', text: '„Vlci zavýjali do noci." – vlci robili skutočnú činnosť' },
      { id: 'b', text: '„Plával ako ryba." – prirovnáva schopnosť plávať k rybe' },
      { id: 'c', text: '„Slnko je žltá guľa." – opisuje slnko priamo' },
      { id: 'd', text: '„Čítal som celý večer." – hovorí o čase' },
    ],
    answer: 'b',
    explanation: 'Prirovnanie je básnický prostriedok, pri ktorom porovnávame dve veci pomocou slov „ako" alebo „akoby". Príklad: plával ako ryba.',
  },
  {
    id: 'ps2-7',
    subject: 'slovencina',
    topic: 'Literatúra',
    prompt: 'Čo je personifikácia (zosobnenie)?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'Porovnanie dvoch vecí pomocou slova „ako"' },
      { id: 'b', text: 'Pripisovanie ľudských vlastností alebo činností neživým veciam alebo zvieratám' },
      { id: 'c', text: 'Opakovanie hlások na konci veršov' },
      { id: 'd', text: 'Prenesenie významu slova na základe podobnosti' },
    ],
    answer: 'b',
    explanation: 'Personifikácia (zosobnenie) znamená, že neživá vec alebo zviera dostáva ľudské vlastnosti, napr. „Vietor sa smial a tancoval po streche."',
  },
  {
    id: 'ps2-8',
    subject: 'slovencina',
    topic: 'Literatúra',
    prompt: 'Ktorá z nasledujúcich ukážok obsahuje metaforu?',
    type: 'choice',
    choices: [
      { id: 'a', text: '„Bežal tak rýchlo ako vietor."' },
      { id: 'b', text: '„More kričalo a búšilo do brehov."' },
      { id: 'c', text: '„Jej vlasy sú zlatom." (bez slova „ako")' },
      { id: 'd', text: '„Prišiel domov neskoro."' },
    ],
    answer: 'c',
    explanation: 'Metafora prenáša význam bez porovnávacích slov: „Jej vlasy sú zlatom" (nie „ako zlato"). Možnosť a) je prirovnanie, b) je personifikácia.',
  },
  {
    id: 'ps2-9',
    subject: 'slovencina',
    topic: 'Literatúra',
    prompt: 'Čo je rozdiel medzi autorom a rozprávačom?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'Autor aj rozprávač sú vždy tá istá osoba' },
      { id: 'b', text: 'Autor je skutočná osoba, ktorá dielo napísala; rozprávač je postava (hlas) v samotnom texte' },
      { id: 'c', text: 'Rozprávač je autor, ktorý vystupuje pod pseudonymom' },
      { id: 'd', text: 'Autor recituje báseň, rozprávač ju píše' },
    ],
    answer: 'b',
    explanation: 'Autor je reálna osoba (napr. Ján Navrátil), ktorá napísala knihu. Rozprávač je hlas vnútri príbehu – môže, ale nemusí byť totožný s autorom.',
  },
  {
    id: 'ps2-10',
    subject: 'slovencina',
    topic: 'Literatúra',
    prompt: 'Ktoré z nasledujúcich patrí medzi lyrické básnické žánre (poézia)?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'román' },
      { id: 'b', text: 'novela' },
      { id: 'c', text: 'sonnet (znelka)' },
      { id: 'd', text: 'kronika' },
    ],
    answer: 'c',
    explanation: 'Sonnet (znelka) je pevná básnická forma s 14 veršami – patrí do poézie. Román, novela aj kronika sú prozaické žánre.',
  },

  // ── SKLADBA VETY ────────────────────────────────────────────────────────────

  {
    id: 'ps2-11',
    subject: 'slovencina',
    topic: 'Skladba vety',
    prompt: 'Vo vete „Starý dedko pomaly kráča po záhrade." je príslovkové určenie miesta:',
    type: 'choice',
    choices: [
      { id: 'a', text: 'starý' },
      { id: 'b', text: 'dedko' },
      { id: 'c', text: 'pomaly' },
      { id: 'd', text: 'po záhrade' },
    ],
    answer: 'd',
    explanation: 'Príslovkové určenie miesta odpovedá na otázku „kde?" alebo „kudy?". Kráča kudy? – po záhrade. Slovo „pomaly" je príslovkové určenie spôsobu.',
  },
  {
    id: 'ps2-12',
    subject: 'slovencina',
    topic: 'Skladba vety',
    prompt: 'Aký vetný člen je slovo „pekné" vo vete „Deti kreslili pekné obrázky."?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'podmet' },
      { id: 'b', text: 'prísudok' },
      { id: 'c', text: 'predmet' },
      { id: 'd', text: 'prívlastok' },
    ],
    answer: 'd',
    explanation: 'Prívlastok bližšie určuje podstatné meno. Aké obrázky? – pekné. Je to prívlastok zhodný.',
  },
  {
    id: 'ps2-13',
    subject: 'slovencina',
    topic: 'Skladba vety',
    prompt: 'Vo vete „Učiteľka vysvetľuje žiakom novú látku." je prísudok:',
    type: 'choice',
    choices: [
      { id: 'a', text: 'učiteľka' },
      { id: 'b', text: 'vysvetľuje' },
      { id: 'c', text: 'žiakom' },
      { id: 'd', text: 'novú' },
    ],
    answer: 'b',
    explanation: 'Prísudok je sloveso, ktoré hovorí, čo podmet (učiteľka) robí. Tu je prísudkom „vysvetľuje".',
  },
  {
    id: 'ps2-14',
    subject: 'slovencina',
    topic: 'Skladba vety',
    prompt: 'Ktorý vetný člen odpovedá na otázky „koho? čoho? komu? čomu? koho? čo? ..."?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'podmet' },
      { id: 'b', text: 'prísudok' },
      { id: 'c', text: 'predmet' },
      { id: 'd', text: 'prívlastok' },
    ],
    answer: 'c',
    explanation: 'Predmet je rozvíjajúci vetný člen závislý od slovesa; odpovedá na otázky jednotlivých pádov (koho?, čo?, komu?, čomu? atď.).',
  },
  {
    id: 'ps2-15',
    subject: 'slovencina',
    topic: 'Skladba vety',
    prompt: 'Vo vete „Ráno sme jedli teplú kašu." odpovedá slovo „ráno" na otázku:',
    type: 'choice',
    choices: [
      { id: 'a', text: 'kde?' },
      { id: 'b', text: 'kedy?' },
      { id: 'c', text: 'ako?' },
      { id: 'd', text: 'prečo?' },
    ],
    answer: 'b',
    explanation: '„Ráno" odpovedá na otázku „kedy?" – ide o príslovkové určenie času.',
  },

  // ── ČÍTANIE S POROZUMENÍM ───────────────────────────────────────────────────

  {
    id: 'ps2-16',
    subject: 'slovencina',
    topic: 'Čítanie s porozumením',
    prompt:
      'Prečítaj si text:\n\n„Zuzka sa zobudila skoro ráno a prvé, čo urobila, bolo, že sa pozrela z okna. Záhrada bola pokrytá hrubou vrstvou bieleho snehu a na konároch viseli ľadové cencúle. Zuzka sa usmiala – dlho čakala na takú zimu."\n\nAký bol počasí v záhrade, keď sa Zuzka zobudila?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'Pršalo a fúkal silný vietor.' },
      { id: 'b', text: 'Snehovalo a bolo mrazivo.' },
      { id: 'c', text: 'Svietilo slnko a bolo teplo.' },
      { id: 'd', text: 'Záhrada bola zahalená hmlou.' },
    ],
    answer: 'b',
    explanation: 'Text hovorí o hrubej vrstve snehu a ľadových cencúľoch – to sú znaky snehovej, mrazivej zimy.',
  },
  {
    id: 'ps2-17',
    subject: 'slovencina',
    topic: 'Čítanie s porozumením',
    prompt:
      'Prečítaj si text:\n\n„Tomáš dlho premýšľal, kým vybral darček pre mamu. Nakoniec sa rozhodol, že jej upečie jej obľúbený jablkový koláč. Mama keď prišla domov a uvidela koláč na stole, objala ho pevne a povedala, že je to najkrajší darček, aký kedy dostala."\n\nPrečo bol darček pre mamu taký výnimočný?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'Bol veľmi drahý.' },
      { id: 'b', text: 'Tomáš ho vyrobil sám s láskou.' },
      { id: 'c', text: 'Mama dostala veľa drahých šperkov.' },
      { id: 'd', text: 'Koláč kúpil v obchode.' },
    ],
    answer: 'b',
    explanation: 'Mama povedala, že je to najkrajší darček – nie preto, že bol drahý, ale preto, že ho Tomáš upiekol sám, s osobným úsilím a láskou.',
  },
  {
    id: 'ps2-18',
    subject: 'slovencina',
    topic: 'Čítanie s porozumením',
    prompt:
      'Prečítaj si text:\n\n„Kaštieľ stál na okraji lesa celé storočia. Hovorilo sa, že v jeho pivniciach je ukrytý poklad dávneho rytiera. Mnohí hľadači sa o poklad pokúšali, no všetci odišli s prázdnymi rukami."\n\nČo je hlavnou témou textu?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'Opis prírody okolo lesa' },
      { id: 'b', text: 'Legenda o ukrytom poklade v starom kaštieli' },
      { id: 'c', text: 'Život dávneho rytiera' },
      { id: 'd', text: 'Stavba kaštieľa' },
    ],
    answer: 'b',
    explanation: 'Celý text sa točí okolo starej legendy o ukrytom poklade – to je ústredná téma.',
  },
  {
    id: 'ps2-19',
    subject: 'slovencina',
    topic: 'Čítanie s porozumením',
    prompt:
      'Prečítaj si text:\n\n„Líška prebiehala lesom a niesla v zuboch čerstvú rybu. Zrazu zbadala vranu sediacu na konári. Vrana mala v zobáku kúsok syra. Líška zastavila a začala vrane lichotivo hovoriť o jej krásnom hlase."\n\nAký je pravdepodobný zámer líšky?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'Chce sa s vranou spriateliť.' },
      { id: 'b', text: 'Chce vráne povedať, kde je ryba.' },
      { id: 'c', text: 'Chce, aby vrana otvorila zobák a pustila syr.' },
      { id: 'd', text: 'Chce vrane pomôcť naučiť sa spievať.' },
    ],
    answer: 'c',
    explanation: 'Toto je motív známej bájky – líška lichotí vrane, aby otvorila zobák a zaaspievala, čím syr vypadne na zem.',
  },

  // ── FRAZEOLOGIZMY ───────────────────────────────────────────────────────────

  {
    id: 'ps2-20',
    subject: 'slovencina',
    topic: 'Frazeologizmy',
    prompt: 'Čo znamená frazeologizmus „byť za vodou"?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'byť mokrý po daždi' },
      { id: 'b', text: 'byť v bezpečí, mať sa výborne, nemať starosti' },
      { id: 'c', text: 'plaviť sa na lodi' },
      { id: 'd', text: 'byť ďaleko od domova' },
    ],
    answer: 'b',
    explanation: '„Byť za vodou" znamená byť v pohodlnej situácii, zabezpečený, bez veľkých starostí o budúcnosť.',
  },
  {
    id: 'ps2-21',
    subject: 'slovencina',
    topic: 'Frazeologizmy',
    prompt: 'Čo znamená frazeologizmus „pasovať ako päsť na oko"?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'dokonale sedieť, byť ideálnou voľbou' },
      { id: 'b', text: 'vôbec nesedieť, byť nevhodný alebo neladný' },
      { id: 'c', text: 'bolieť päsť aj oko súčasne' },
      { id: 'd', text: 'byť dobrým boxerom' },
    ],
    answer: 'b',
    explanation: '„Pasovať ako päsť na oko" sa používa ironicky – päsť na oko samozrejme nepasuje, preto frazeologizmus znamená, že niečo je úplne nevhodné alebo neladí.',
  },
  {
    id: 'ps2-22',
    subject: 'slovencina',
    topic: 'Frazeologizmy',
    prompt: 'Čo znamená frazeologizmus „spadnúť z višne"?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'byť veľmi prekvapený príjemnou správou' },
      { id: 'b', text: 'zraniť sa pri páde' },
      { id: 'c', text: 'byť naivný, neorientovať sa v situácii, nevedieť o veciach, ktoré sú bežne známe' },
      { id: 'd', text: 'obľubovať višne' },
    ],
    answer: 'c',
    explanation: '„Spadnúť z višne" alebo „byť ako spadnutý z višne" znamená neorientovať sa, nevyznať sa v bežných veciach – byť naivný alebo neinformovaný.',
  },
  {
    id: 'ps2-23',
    subject: 'slovencina',
    topic: 'Frazeologizmy',
    prompt: 'Čo znamená frazeologizmus „dať komu košom"?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'dať niekomu darček v košíku' },
      { id: 'b', text: 'odmietnuť niekoho (napr. nápadníka), zavrhnúť ponuku' },
      { id: 'c', text: 'pomôcť niekomu odniesť nákup' },
      { id: 'd', text: 'víťaziť v hre basketbal' },
    ],
    answer: 'b',
    explanation: '„Dať košom" znamená odmietnuť – najčastejšie v súvislosti s odmietnutím nápadníka alebo ponuky.',
  },
  {
    id: 'ps2-24',
    subject: 'slovencina',
    topic: 'Frazeologizmy',
    prompt: 'Čo znamená frazeologizmus „byť v siedmom nebi"?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'byť veľmi smutný a sklamaný' },
      { id: 'b', text: 'byť chorý a ležať v posteli' },
      { id: 'c', text: 'byť nesmierně šťastný, prežívať veľkú radosť' },
      { id: 'd', text: 'bývať na siedmom poschodí' },
    ],
    answer: 'c',
    explanation: '„Byť v siedmom nebi" znamená prežívať obrovskú radosť a šťastie – sedmé nebo bolo v starých predstavách miestom najvyššieho blaženstva.',
  },

  // ── DELENIE SLOV NA SLABIKY ──────────────────────────────────────────────────

  {
    id: 'ps2-25',
    subject: 'slovencina',
    topic: 'Delenie slov na slabiky',
    prompt: 'Koľko slabík má slovo „záhrada"?',
    type: 'choice',
    choices: [
      { id: 'a', text: '2' },
      { id: 'b', text: '3' },
      { id: 'c', text: '4' },
      { id: 'd', text: '5' },
    ],
    answer: 'b',
    explanation: 'Slovo sa delí: zá-hra-da → 3 slabiky.',
  },
  {
    id: 'ps2-26',
    subject: 'slovencina',
    topic: 'Delenie slov na slabiky',
    prompt: 'Ako správne rozdelíme slovo „učiteľka" pri zalomení riadka?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'u-čiteľka' },
      { id: 'b', text: 'uči-teľ-ka' },
      { id: 'c', text: 'učiteľ-ka' },
      { id: 'd', text: 'u-či-teľ-ka' },
    ],
    answer: 'd',
    explanation: 'Slovo „učiteľka" má 4 slabiky: u-či-teľ-ka. Každé rozdelenie musí byť na hranici slabík.',
  },
  {
    id: 'ps2-27',
    subject: 'slovencina',
    topic: 'Delenie slov na slabiky',
    prompt: 'Koľko slabík má slovo „priateľstvo"?',
    type: 'choice',
    choices: [
      { id: 'a', text: '2' },
      { id: 'b', text: '3' },
      { id: 'c', text: '4' },
      { id: 'd', text: '5' },
    ],
    answer: 'b',
    explanation: 'Slovo sa delí: pria-teľ-stvo. Dvojhláska „ia" tvorí jednu slabiku, preto „pria" je prvá slabika. Celkovo 3 slabiky: pria | teľ | stvo.',
  },
  {
    id: 'ps2-28',
    subject: 'slovencina',
    topic: 'Delenie slov na slabiky',
    prompt: 'Ako sa správne rozdelí slovo „slovenčina" pri zalomení riadka?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'slov-enčina' },
      { id: 'b', text: 'slo-ven-či-na' },
      { id: 'c', text: 'slovenči-na' },
      { id: 'd', text: 'slove-nčina' },
    ],
    answer: 'b',
    explanation: 'Slovo „slovenčina" má 4 slabiky: slo-ven-či-na. Správne delenie je na hraniciach slabík.',
  },

  // ── HLÁSKY ──────────────────────────────────────────────────────────────────

  {
    id: 'ps2-29',
    subject: 'slovencina',
    topic: 'Hlásky',
    prompt: 'Ktoré z nasledujúcich sú slovenské dvojhlásky?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'ai, ei, oi' },
      { id: 'b', text: 'ia, ie, iu, ô' },
      { id: 'c', text: 'au, eu, ou' },
      { id: 'd', text: 'ia, ie, iu, ui' },
    ],
    answer: 'b',
    explanation: 'Slovenské dvojhlásky sú: ia, ie, iu a ô (= uo). Nie sú nimi napríklad ai, ei ani ui.',
  },
  {
    id: 'ps2-30',
    subject: 'slovencina',
    topic: 'Hlásky',
    prompt: 'Ktoré spoluhlásky patria medzi mäkké (vždy mäkké) spoluhlásky v slovenčine?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'h, ch, k, g' },
      { id: 'b', text: 'd, t, n, l' },
      { id: 'c', text: 'ď, ť, ň, ľ, č, š, ž, j, dž' },
      { id: 'd', text: 'b, p, m, v, f' },
    ],
    answer: 'c',
    explanation: 'Mäkké spoluhlásky sú: ď, ť, ň, ľ, č, š, ž, j, dž – po nich sa vždy píše mäkké i. Obojaké sú d, t, n, l (môžu byť tvrdé aj mäkké podľa polohy).',
  },
  {
    id: 'ps2-31',
    subject: 'slovencina',
    topic: 'Hlásky',
    prompt: 'Koľko samohlások (vrátane dlhých) obsahuje slovo „múdrosť"?',
    type: 'choice',
    choices: [
      { id: 'a', text: '1' },
      { id: 'b', text: '2' },
      { id: 'c', text: '3' },
      { id: 'd', text: '4' },
    ],
    answer: 'b',
    explanation: 'V slove „múdrosť" sú samohlásky: ú a o. Ostatné hlásky (m, d, r, s, ť) sú spoluhlásky. Celkovo 2 samohlásky.',
  },
  {
    id: 'ps2-32',
    subject: 'slovencina',
    topic: 'Hlásky',
    prompt: 'Ktoré tvrdenie o rytme v básni je správne?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'Rytmus je zvuková zhoda na konci veršov.' },
      { id: 'b', text: 'Rytmus je pravidelné striedanie prízvučných a neprízvučných slabík v básni.' },
      { id: 'c', text: 'Rytmus znamená, že básne musia byť dlhé.' },
      { id: 'd', text: 'Rytmus je druh básne bez rýmu.' },
    ],
    answer: 'b',
    explanation: 'Rytmus je zvuková pravidelnosť básne – striedanie prízvučných a neprízvučných slabík. Zvukovú zhodu na konci veršov nazývame rým.',
  },

  // ── PRIAMA REČ ───────────────────────────────────────────────────────────────

  {
    id: 'ps2-33',
    subject: 'slovencina',
    topic: 'Priama reč',
    prompt: 'Ktorá veta s priamou rečou je napísaná správne?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'Mama povedala: Poď jesť!' },
      { id: 'b', text: 'Mama povedala: „Poď jesť!"' },
      { id: 'c', text: 'Mama povedala, „Poď jesť!"' },
      { id: 'd', text: '„Mama povedala: Poď jesť."' },
    ],
    answer: 'b',
    explanation: 'Pred priamou rečou sa píše dvojbodka a priama reč sa uzatvára do slovenských úvodzoviek „ ". Správny zápis: Mama povedala: „Poď jesť!"',
  },
  {
    id: 'ps2-34',
    subject: 'slovencina',
    topic: 'Priama reč',
    prompt: 'Ako sa zapisuje priama reč, keď uvádzacia veta nasleduje AŽ ZA priamou rečou? Vyber správny príklad.',
    type: 'choice',
    choices: [
      { id: 'a', text: '„Poď domov," povedal otec.' },
      { id: 'b', text: '„Poď domov." povedal otec.' },
      { id: 'c', text: '„Poď domov" – povedal otec.' },
      { id: 'd', text: 'Povedal otec „Poď domov."' },
    ],
    answer: 'a',
    explanation: 'Keď uvádzacia veta nasleduje za priamou rečou a priama reč by mala bodku, nahradíme bodku čiarkou ešte vnútri úvodzoviek: „Poď domov," povedal otec.',
  },
  {
    id: 'ps2-35',
    subject: 'slovencina',
    topic: 'Priama reč',
    prompt: 'Čo je uvádzacia veta pri priamej reči?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'Veta v úvodzovkách, ktorú niekto hovorí' },
      { id: 'b', text: 'Veta, ktorá hovorí, kto a ako prehovoril (napr. „Peter povedal", „mama spýtala sa")' },
      { id: 'c', text: 'Prvá veta každého odseku' },
      { id: 'd', text: 'Nadpis nad priamou rečou' },
    ],
    answer: 'b',
    explanation: 'Uvádzacia veta uvádza priamu reč – hovorí, kto hovorí a akým spôsobom (povedal, zvolal, spýtal sa...). Samotná priama reč je v úvodzovkách.',
  },

  // ── ČASTI SLOVA ─────────────────────────────────────────────────────────────

  {
    id: 'ps2-36',
    subject: 'slovencina',
    topic: 'Časti slova',
    prompt: 'Slovo „zápisník" rozlož na časti. Ktorá časť je predpona?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'ník' },
      { id: 'b', text: 'pis' },
      { id: 'c', text: 'zá' },
      { id: 'd', text: 'zápisník nemá predponu' },
    ],
    answer: 'c',
    explanation: 'Slovo „zápisník" sa skladá z predpony zá-, koreňa -pis-, prípony -ník a nulovej koncovky. Predpona je „zá-".',
  },
  {
    id: 'ps2-37',
    subject: 'slovencina',
    topic: 'Časti slova',
    prompt: 'Čo je koreň slova?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'Časť slova, ktorá sa pridáva pred základnú časť' },
      { id: 'b', text: 'Spoločná základná časť príbuzných slov, ktorá nesie hlavný význam' },
      { id: 'c', text: 'Menná prípona alebo slovesná koncovka na konci slova' },
      { id: 'd', text: 'Posledná hláska každého slova' },
    ],
    answer: 'b',
    explanation: 'Koreň (základ) je spoločná časť príbuzných slov – napr. v slovách les, lesník, lesný, prales je koreň „les-".',
  },
  {
    id: 'ps2-38',
    subject: 'slovencina',
    topic: 'Časti slova',
    prompt: 'Ktoré zo slov obsahuje predponu „od-"?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'odísť' },
      { id: 'b', text: 'odo' },
      { id: 'c', text: 'obsah' },
      { id: 'd', text: 'okno' },
    ],
    answer: 'a',
    explanation: '„Odísť" = predpona od- + koreň -ísť. Ostatné slová (odo, obsah, okno) predponu od- neobsahujú – začínajú sa na „o", ale celé „od-" ako predpona tam nie je.',
  },
  {
    id: 'ps2-39',
    subject: 'slovencina',
    topic: 'Časti slova',
    prompt: 'Čo je koncovka slova?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'Časť slova pred koreňom, ktorá mení alebo bližšie určuje jeho význam' },
      { id: 'b', text: 'Časť slova za koreňom, ktorá sa pri skloňovaní alebo časovaní mení' },
      { id: 'c', text: 'Spoločná časť príbuzných slov' },
      { id: 'd', text: 'Každá posledná slabika slova' },
    ],
    answer: 'b',
    explanation: 'Koncovka je ohybná časť slova, ktorá sa mení pri skloňovaní (podstatné a prídavné mená) alebo časovaní (slovesá). Napr. žia-k → žiaka, žiakovi... – koncovka sa mení.',
  },

  // ── ĎALŠIE KOMBINOVANÉ / ZLOŽITEJŠIE OTÁZKY ────────────────────────────────

  {
    id: 'ps2-40',
    subject: 'slovencina',
    topic: 'Literatúra',
    prompt:
      'Prečítaj si úryvok:\n\n„Mesiac sa pozeral z oblakov ako strieborné oko noci. Stromy šepkali tajomstvá a vietor im odpovedal jemným vzdychom."\n\nKtorý básnický prostriedok PREVLÁDA v tomto úryvku?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'prirovnanie – porovnáva mesiac pomocou slova „ako"' },
      { id: 'b', text: 'personifikácia – stromy šepkajú, vietor odpovedá, mesiac sa pozerá' },
      { id: 'c', text: 'rým – verše sa rýmujú' },
      { id: 'd', text: 'rytmus – pravidelné striedanie slabík' },
    ],
    answer: 'b',
    explanation: 'V úryvku prevláda personifikácia: mesiac sa pozerá, stromy šepkajú, vietor odpovedá – neživé veci konajú ako ľudia. Veta „ako strieborné oko noci" je síce prirovnanie, no celkovo dominuje personifikácia.',
  },
];
