import type { Question } from './questions';

export const pack: Question[] = [
  {
    id: 'pm2-1',
    subject: 'matematika',
    topic: 'Geometria – obvod štvorca',
    prompt: 'Štvorec má stranu 9 cm. Aký je jeho obvod (v cm)?',
    type: 'text',
    answer: '36',
    explanation: 'O = 4 · a = 4 · 9 = 36 cm.',
  },
  {
    id: 'pm2-2',
    subject: 'matematika',
    topic: 'Geometria – obsah obdĺžnika',
    prompt: 'Obdĺžnik má strany 12 cm a 4 cm. Aký je jeho obsah (v cm²)?',
    type: 'text',
    answer: '48',
    explanation: 'S = a · b = 12 · 4 = 48 cm².',
  },
  {
    id: 'pm2-3',
    subject: 'matematika',
    topic: 'Geometria – uhly',
    prompt: 'Uhol s veľkosťou 120° je:',
    type: 'choice',
    choices: [
      { id: 'a', text: 'ostrý' },
      { id: 'b', text: 'pravý' },
      { id: 'c', text: 'tupý' },
      { id: 'd', text: 'priamy' },
    ],
    answer: 'c',
    explanation: 'Tupý uhol má veľkosť väčšiu ako 90° a menšiu ako 180°.',
  },
  {
    id: 'pm2-4',
    subject: 'matematika',
    topic: 'Geometria – uhly',
    prompt: 'Uhol s veľkosťou 45° je:',
    type: 'choice',
    choices: [
      { id: 'a', text: 'ostrý' },
      { id: 'b', text: 'pravý' },
      { id: 'c', text: 'tupý' },
      { id: 'd', text: 'priamy' },
    ],
    answer: 'a',
    explanation: 'Ostrý uhol má veľkosť menšiu ako 90°.',
  },
  {
    id: 'pm2-5',
    subject: 'matematika',
    topic: 'Geometria – obvod trojuholníka',
    prompt: 'Trojuholník má strany 7 cm, 9 cm a 11 cm. Aký je jeho obvod (v cm)?',
    type: 'text',
    answer: '27',
    explanation: 'Obvod = 7 + 9 + 11 = 27 cm.',
  },
  {
    id: 'pm2-6',
    subject: 'matematika',
    topic: 'Jednotky dĺžky',
    prompt: 'Koľko milimetrov je 5 cm?',
    type: 'text',
    answer: '50',
    explanation: '1 cm = 10 mm, takže 5 cm = 50 mm.',
  },
  {
    id: 'pm2-7',
    subject: 'matematika',
    topic: 'Jednotky dĺžky',
    prompt: 'Koľko metrov je 3 km a 250 m?',
    type: 'text',
    answer: '3250',
    acceptable: ['3 250'],
    explanation: '3 km = 3000 m; 3000 + 250 = 3250 m.',
  },
  {
    id: 'pm2-8',
    subject: 'matematika',
    topic: 'Jednotky hmotnosti',
    prompt: 'Koľko gramov je 2,5 kg?',
    type: 'text',
    answer: '2500',
    acceptable: ['2 500'],
    explanation: '1 kg = 1000 g, takže 2,5 kg = 2500 g.',
  },
  {
    id: 'pm2-9',
    subject: 'matematika',
    topic: 'Jednotky hmotnosti',
    prompt: 'Koľko kilogramov má 1 tona?',
    type: 'text',
    answer: '1000',
    acceptable: ['1 000'],
    explanation: '1 t = 1000 kg.',
  },
  {
    id: 'pm2-10',
    subject: 'matematika',
    topic: 'Jednotky objemu',
    prompt: 'Koľko mililitrov je 3 dl?',
    type: 'text',
    answer: '300',
    explanation: '1 dl = 100 ml, takže 3 dl = 300 ml.',
  },
  {
    id: 'pm2-11',
    subject: 'matematika',
    topic: 'Jednotky objemu',
    prompt: 'Koľko litrov je 2 hl?',
    type: 'text',
    answer: '200',
    explanation: '1 hl = 100 l, takže 2 hl = 200 l.',
  },
  {
    id: 'pm2-12',
    subject: 'matematika',
    topic: 'Jednotky času',
    prompt: 'Koľko sekúnd má 3 minúty?',
    type: 'text',
    answer: '180',
    explanation: '1 min = 60 s, takže 3 · 60 = 180 s.',
  },
  {
    id: 'pm2-13',
    subject: 'matematika',
    topic: 'Jednotky času',
    prompt: 'Koľko hodín má 2 dni a 6 hodín?',
    type: 'text',
    answer: '54',
    explanation: '2 dni = 48 h; 48 + 6 = 54 hodín.',
  },
  {
    id: 'pm2-14',
    subject: 'matematika',
    topic: 'Peniaze',
    prompt: 'Zmrzlina stojí 1,30 €. Koľko zaplatíš za 5 zmrzlín?',
    type: 'text',
    answer: '6,50',
    acceptable: ['6.50', '6,50 €', '6.5', '6,5'],
    explanation: '5 · 1,30 = 6,50 €.',
  },
  {
    id: 'pm2-15',
    subject: 'matematika',
    topic: 'Peniaze – výdavok',
    prompt: 'Zaplatila si bankovkou 20 € za nákup vo výške 13,40 €. Koľko € ti vrátia?',
    type: 'text',
    answer: '6,60',
    acceptable: ['6.60', '6,60 €', '6.6', '6,6'],
    explanation: '20 − 13,40 = 6,60 €.',
  },
  {
    id: 'pm2-16',
    subject: 'matematika',
    topic: 'Peniaze – centy',
    prompt: 'Koľko centov má 4,75 €?',
    type: 'text',
    answer: '475',
    explanation: '1 € = 100 centov; 4,75 · 100 = 475 centov.',
  },
  {
    id: 'pm2-17',
    subject: 'matematika',
    topic: 'Čas – hodiny',
    prompt: 'Hodiny ukazujú 9:50. O koľko minút bude 10:30?',
    type: 'text',
    answer: '40',
    explanation: 'Z 9:50 do 10:00 je 10 min, z 10:00 do 10:30 je 30 min, spolu 40 min.',
  },
  {
    id: 'pm2-18',
    subject: 'matematika',
    topic: 'Kalendár',
    prompt: 'Ak je dnes utorok, aký deň bude o 10 dní?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'pondelok' },
      { id: 'b', text: 'utorok' },
      { id: 'c', text: 'štvrtok' },
      { id: 'd', text: 'piatok' },
    ],
    answer: 'd',
    explanation: '10 dní = 7 + 3 dni. O 7 dní je opäť utorok, o 3 dni neskôr je piatok.',
  },
  {
    id: 'pm2-19',
    subject: 'matematika',
    topic: 'Kalendár',
    prompt: 'Koľko dní má február v priestupnom roku?',
    type: 'text',
    answer: '29',
    explanation: 'V priestupnom roku má február 29 dní.',
  },
  {
    id: 'pm2-20',
    subject: 'matematika',
    topic: 'Postupnosť',
    prompt: 'Doplň ďalšie číslo: 3, 7, 11, 15, …',
    type: 'text',
    answer: '19',
    explanation: 'Pripočítavame 4: 15 + 4 = 19.',
  },
  {
    id: 'pm2-21',
    subject: 'matematika',
    topic: 'Postupnosť',
    prompt: 'Doplň ďalšie číslo: 1, 3, 9, 27, …',
    type: 'text',
    answer: '81',
    explanation: 'Každé číslo je 3-násobkom predchádzajúceho: 27 · 3 = 81.',
  },
  {
    id: 'pm2-22',
    subject: 'matematika',
    topic: 'Postupnosť',
    prompt: 'Doplň ďalšie číslo: 50, 45, 40, 35, …',
    type: 'text',
    answer: '30',
    explanation: 'Odčítavame 5: 35 − 5 = 30.',
  },
  {
    id: 'pm2-23',
    subject: 'matematika',
    topic: 'Logika – kombinácie',
    prompt:
      'Lucia má 3 tričká (biele, modré, červené) a 2 sukne (čiernu, sivú). Koľko rôznych kombinácií tričko + sukňa si môže obliecť?',
    type: 'text',
    answer: '6',
    explanation: '3 · 2 = 6 kombinácií.',
  },
  {
    id: 'pm2-24',
    subject: 'matematika',
    topic: 'Logika – mince',
    prompt:
      'Maťo má 7 mincí v hodnote 50 centov a 1 €. Spolu má 5 €. Koľko má 1-eurových mincí?',
    type: 'text',
    answer: '3',
    explanation:
      'Označme jednoeurovky x. Potom x + 0,5 · (7 − x) = 5 → 0,5x + 3,5 = 5 → 0,5x = 1,5 → x = 3.',
  },
  {
    id: 'pm2-25',
    subject: 'matematika',
    topic: 'Logika – vek',
    prompt:
      'Brat je o 4 roky starší ako sestra. Spolu majú 22 rokov. Koľko rokov má sestra?',
    type: 'text',
    answer: '9',
    explanation: 's + (s + 4) = 22 → 2s = 18 → s = 9 rokov.',
  },
  {
    id: 'pm2-26',
    subject: 'matematika',
    topic: 'Zaokrúhľovanie',
    prompt: 'Zaokrúhli číslo 357 na desiatky.',
    type: 'text',
    answer: '360',
    explanation: 'Číslica jednotiek je 7 ⇒ zaokrúhľujeme nahor na 360.',
  },
  {
    id: 'pm2-27',
    subject: 'matematika',
    topic: 'Zaokrúhľovanie',
    prompt: 'Zaokrúhli číslo 6 482 na tisíce.',
    type: 'text',
    answer: '6000',
    acceptable: ['6 000'],
    explanation: 'Číslica stoviek je 4 ⇒ zaokrúhľujeme nadol na 6 000.',
  },
  {
    id: 'pm2-28',
    subject: 'matematika',
    topic: 'Porovnávanie čísel',
    prompt: 'Ktoré z čísel je najväčšie?',
    type: 'choice',
    choices: [
      { id: 'a', text: '8 909' },
      { id: 'b', text: '8 990' },
      { id: 'c', text: '9 089' },
      { id: 'd', text: '8 999' },
    ],
    answer: 'c',
    explanation: '9 089 začína cifrou 9 v tisícoch, ostatné cifrou 8.',
  },
  {
    id: 'pm2-29',
    subject: 'matematika',
    topic: 'Porovnávanie – usporiadanie',
    prompt:
      'Usporiadaj čísla od najmenšieho po najväčšie: 2 305, 2 035, 2 350, 2 053. Ktoré je tretie v poradí?',
    type: 'text',
    answer: '2305',
    acceptable: ['2 305'],
    explanation: 'Poradie: 2 035, 2 053, 2 305, 2 350. Tretie je 2 305.',
  },
  {
    id: 'pm2-30',
    subject: 'matematika',
    topic: 'Deliteľnosť',
    prompt: 'Ktoré z týchto čísel je deliteľné 5?',
    type: 'choice',
    choices: [
      { id: 'a', text: '342' },
      { id: 'b', text: '517' },
      { id: 'c', text: '690' },
      { id: 'd', text: '208' },
    ],
    answer: 'c',
    explanation: 'Číslo je deliteľné 5, ak končí na 0 alebo 5. 690 končí 0.',
  },
  {
    id: 'pm2-31',
    subject: 'matematika',
    topic: 'Deliteľnosť',
    prompt: 'Ktoré z týchto čísel je deliteľné 3?',
    type: 'choice',
    choices: [
      { id: 'a', text: '124' },
      { id: 'b', text: '231' },
      { id: 'c', text: '407' },
      { id: 'd', text: '550' },
    ],
    answer: 'b',
    explanation: 'Súčet cifier 2+3+1 = 6, je deliteľný 3, takže aj 231 je deliteľné 3.',
  },
  {
    id: 'pm2-32',
    subject: 'matematika',
    topic: 'Párne / nepárne',
    prompt: 'Koľko párnych čísel je medzi číslami od 1 po 20 (vrátane)?',
    type: 'text',
    answer: '10',
    explanation: 'Párne sú: 2, 4, 6, 8, 10, 12, 14, 16, 18, 20 – spolu 10.',
  },
  {
    id: 'pm2-33',
    subject: 'matematika',
    topic: 'Geometria – obvod',
    prompt:
      'Záhrada v tvare obdĺžnika má strany 25 m a 15 m. Koľko metrov pletiva treba na jej oplotenie?',
    type: 'text',
    answer: '80',
    explanation: 'O = 2 · (25 + 15) = 2 · 40 = 80 m.',
  },
  {
    id: 'pm2-34',
    subject: 'matematika',
    topic: 'Geometria – obsah',
    prompt:
      'Izba má tvar štvorca so stranou 4 m. Koľko m² koberca treba na jej pokrytie?',
    type: 'text',
    answer: '16',
    explanation: 'S = a · a = 4 · 4 = 16 m².',
  },
  {
    id: 'pm2-35',
    subject: 'matematika',
    topic: 'Čas – trvanie',
    prompt:
      'Tréning sa začal o 16:40 a trval 1 hodinu a 35 minút. O koľkej skončil?',
    type: 'text',
    answer: '18:15',
    explanation: '16:40 + 1 h = 17:40; 17:40 + 35 min = 18:15.',
  },
  {
    id: 'pm2-36',
    subject: 'matematika',
    topic: 'Logika – počítanie',
    prompt:
      'Koľko dvojciferných čísel sa dá zostaviť z cifier 3, 5, 7, ak sa cifry nesmú opakovať?',
    type: 'text',
    answer: '6',
    explanation: 'Prvá cifra: 3 možnosti, druhá: 2 možnosti. Spolu 3 · 2 = 6.',
  },
  {
    id: 'pm2-37',
    subject: 'matematika',
    topic: 'Logika – deduktívna úloha',
    prompt:
      'Petra je staršia ako Ema, ale mladšia ako Klára. Klára nie je najstaršia – najstaršia je Sára. Kto je najmladší?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'Petra' },
      { id: 'b', text: 'Ema' },
      { id: 'c', text: 'Klára' },
      { id: 'd', text: 'Sára' },
    ],
    answer: 'b',
    explanation: 'Z poradia Ema < Petra < Klára < Sára vyplýva, že najmladšia je Ema.',
  },
  {
    id: 'pm2-38',
    subject: 'matematika',
    topic: 'Postupnosť – druhé mocniny',
    prompt: 'Aké číslo nasleduje? 4, 9, 16, 25, 36, …',
    type: 'text',
    answer: '49',
    explanation: 'Sú to druhé mocniny 2², 3², 4², 5², 6², 7² = 49.',
  },
  {
    id: 'pm2-39',
    subject: 'matematika',
    topic: 'Logika – slovná úloha',
    prompt:
      'V košíku je 24 vajec. Tretina je hnedá, polovica zo zvyšku je biela a ostatné sú škvrnité. Koľko škvrnitých vajec je v košíku?',
    type: 'text',
    answer: '8',
    explanation: 'Hnedé: 24 : 3 = 8. Zvyšok: 16. Biele: 16 : 2 = 8. Škvrnité: 16 − 8 = 8.',
  },
  {
    id: 'pm2-40',
    subject: 'matematika',
    topic: 'Logika – peniaze',
    prompt:
      'Kniha stojí 12 €, pero 2 € a zošit 1,50 €. Janka kúpila knihu, 3 perá a 4 zošity. Koľko € zaplatila spolu?',
    type: 'text',
    answer: '24',
    acceptable: ['24,00', '24.00', '24 €'],
    explanation: '12 + 3 · 2 + 4 · 1,50 = 12 + 6 + 6 = 24 €.',
  },
];
