import type { Question } from './questions';

// Doplnkový balík otázok zo slovenčiny – 40 otázok pre 5. ročník ZŠ
// Témy: vybrané slová, slovné druhy, vzory, časy slovies, druhy viet,
// pravopis (veľké písmená, i/y, ie/é, ä, dvojhlásky), synonymá/antonymá, predložky.
export const pack: Question[] = [
  {
    id: 'ps1-1',
    subject: 'slovencina',
    topic: 'Vybrané slová – y/i',
    prompt: 'Doplň správne y/i: „Mama upiekla v_borný koláč."',
    type: 'choice',
    choices: [
      { id: 'a', text: 'výborný' },
      { id: 'b', text: 'víborný' },
    ],
    answer: 'a',
    explanation: 'Slovo „výborný" je odvodené od vybraného slova „vy-" – píše sa s tvrdým ý.',
  },
  {
    id: 'ps1-2',
    subject: 'slovencina',
    topic: 'Vybrané slová – y/i',
    prompt: 'Doplň: „Na lúke kvitnú voňavé l_pové kvety."',
    type: 'choice',
      choices: [
      { id: 'a', text: 'lipové' },
      { id: 'b', text: 'lypové' },
    ],
    answer: 'a',
    explanation: 'Slovo „lipa" sa píše s mäkkým i – nepatrí medzi vybrané slová po l.',
  },
  {
    id: 'ps1-3',
    subject: 'slovencina',
    topic: 'Vybrané slová – y/i',
    prompt: 'Doplň: „R_ba pláva v rieke."',
    type: 'choice',
    choices: [
      { id: 'a', text: 'Riba' },
      { id: 'b', text: 'Ryba' },
    ],
    answer: 'b',
    explanation: '„Ryba" je vybrané slovo po r – píše sa s tvrdým y.',
  },
  {
    id: 'ps1-4',
    subject: 'slovencina',
    topic: 'Vybrané slová – y/i',
    prompt: 'V ktorej dvojici sa obe slová píšu s mäkkým i?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'cisár, ticho' },
      { id: 'b', text: 'syn, mydlo' },
      { id: 'c', text: 'bystrý, pýcha' },
      { id: 'd', text: 'vysoký, zvyk' },
    ],
    answer: 'a',
    explanation: '„Cisár" aj „ticho" sa píšu s mäkkým i – nie sú to vybrané slová.',
  },
  {
    id: 'ps1-5',
    subject: 'slovencina',
    topic: 'Vybrané slová po v',
    prompt: 'Doplň: „V_soká hora sa týči nad dedinou."',
    type: 'choice',
    choices: [
      { id: 'a', text: 'Vísoká' },
      { id: 'b', text: 'Vysoká' },
    ],
    answer: 'b',
    explanation: '„Vysoký" je vybrané slovo po v – píše sa s tvrdým y.',
  },
  {
    id: 'ps1-6',
    subject: 'slovencina',
    topic: 'Slovné druhy',
    prompt: 'Ktoré slovo je zámeno?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'pekný' },
      { id: 'b', text: 'ona' },
      { id: 'c', text: 'spieva' },
      { id: 'd', text: 'rýchlo' },
    ],
    answer: 'b',
    explanation: '„Ona" zastupuje podstatné meno – je to osobné zámeno.',
  },
  {
    id: 'ps1-7',
    subject: 'slovencina',
    topic: 'Slovné druhy',
    prompt: 'Ktoré slovo je predložka?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'pod' },
      { id: 'b', text: 'pes' },
      { id: 'c', text: 'a' },
      { id: 'd', text: 'och' },
    ],
    answer: 'a',
    explanation: '„Pod" je predložka, ktorá sa viaže s podstatným menom (napr. pod stolom).',
  },
  {
    id: 'ps1-8',
    subject: 'slovencina',
    topic: 'Slovné druhy',
    prompt: 'Ktoré slovo je spojka?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'na' },
      { id: 'b', text: 'aj' },
      { id: 'c', text: 'beží' },
      { id: 'd', text: 'jeho' },
    ],
    answer: 'b',
    explanation: 'Spojka „aj" spája slová alebo vety.',
  },
  {
    id: 'ps1-9',
    subject: 'slovencina',
    topic: 'Slovné druhy',
    prompt: 'Ktoré slovo je citoslovce?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'pes' },
      { id: 'b', text: 'haf' },
      { id: 'c', text: 'pekne' },
      { id: 'd', text: 'môj' },
    ],
    answer: 'b',
    explanation: '„Haf" napodobňuje zvuk – je to citoslovce.',
  },
  {
    id: 'ps1-10',
    subject: 'slovencina',
    topic: 'Slovné druhy',
    prompt: 'Ktoré slovo je častica?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'áno' },
      { id: 'b', text: 'auto' },
      { id: 'c', text: 'pri' },
      { id: 'd', text: 'malý' },
    ],
    answer: 'a',
    explanation: '„Áno" je častica – vyjadruje súhlas a nemení tvar.',
  },
  {
    id: 'ps1-11',
    subject: 'slovencina',
    topic: 'Slovné druhy',
    prompt: 'Koľko podstatných mien je vo vete: „Mama kúpila chlieb, mlieko a maslo."?',
    type: 'text',
    answer: '4',
    explanation: 'Podstatné mená: mama, chlieb, mlieko, maslo – spolu 4.',
  },
  {
    id: 'ps1-12',
    subject: 'slovencina',
    topic: 'Vzory – stredný rod',
    prompt: 'Podľa ktorého vzoru sa skloňuje slovo „mesto"?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'mesto' },
      { id: 'b', text: 'srdce' },
      { id: 'c', text: 'vysvedčenie' },
      { id: 'd', text: 'dievča' },
    ],
    answer: 'a',
    explanation: '„Mesto" je samo o sebe vzor pre stredný rod s tvrdým zakončením.',
  },
  {
    id: 'ps1-13',
    subject: 'slovencina',
    topic: 'Vzory – mužský rod',
    prompt: 'Podľa ktorého vzoru sa skloňuje slovo „strom"?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'chlap' },
      { id: 'b', text: 'hrdina' },
      { id: 'c', text: 'dub' },
      { id: 'd', text: 'stroj' },
    ],
    answer: 'c',
    explanation: '„Strom" je neživotné podstatné meno mužského rodu, tvrdé zakončenie – vzor „dub".',
  },
  {
    id: 'ps1-14',
    subject: 'slovencina',
    topic: 'Vzory – mužský rod',
    prompt: 'Podľa ktorého vzoru sa skloňuje slovo „čaj"?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'dub' },
      { id: 'b', text: 'stroj' },
      { id: 'c', text: 'chlap' },
      { id: 'd', text: 'hrdina' },
    ],
    answer: 'b',
    explanation: '„Čaj" je neživotné, mužský rod, mäkké zakončenie – vzor „stroj".',
  },
  {
    id: 'ps1-15',
    subject: 'slovencina',
    topic: 'Vzory – ženský rod',
    prompt: 'Podľa ktorého vzoru sa skloňuje slovo „ulica"?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'žena' },
      { id: 'b', text: 'ulica' },
      { id: 'c', text: 'dlaň' },
      { id: 'd', text: 'kosť' },
    ],
    answer: 'b',
    explanation: '„Ulica" je sama o sebe vzor – ženský rod s mäkkým zakončením.',
  },
  {
    id: 'ps1-16',
    subject: 'slovencina',
    topic: 'Vzory – ženský rod',
    prompt: 'Podľa ktorého vzoru sa skloňuje slovo „báseň"?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'žena' },
      { id: 'b', text: 'ulica' },
      { id: 'c', text: 'dlaň' },
      { id: 'd', text: 'kosť' },
    ],
    answer: 'd',
    explanation: '„Báseň" je ženský rod, v genitíve „básne" – skloňuje sa podľa vzoru „kosť".',
  },
  {
    id: 'ps1-17',
    subject: 'slovencina',
    topic: 'Vzory – mužský rod',
    prompt: 'Podľa ktorého vzoru sa skloňuje slovo „turista"?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'chlap' },
      { id: 'b', text: 'hrdina' },
      { id: 'c', text: 'dub' },
      { id: 'd', text: 'stroj' },
    ],
    answer: 'b',
    explanation: '„Turista" je životné, mužský rod, končí sa na -a – vzor „hrdina".',
  },
  {
    id: 'ps1-18',
    subject: 'slovencina',
    topic: 'Časy slovies',
    prompt: 'V akom čase je veta: „Včera sme čítali knihu."?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'minulý' },
      { id: 'b', text: 'prítomný' },
      { id: 'c', text: 'budúci' },
    ],
    answer: 'a',
    explanation: 'Slovo „včera" a tvar „čítali sme" vyjadrujú minulý čas.',
  },
  {
    id: 'ps1-19',
    subject: 'slovencina',
    topic: 'Časy slovies',
    prompt: 'V akom čase je sloveso vo vete: „Práve píšem domácu úlohu."?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'minulý' },
      { id: 'b', text: 'prítomný' },
      { id: 'c', text: 'budúci' },
    ],
    answer: 'b',
    explanation: 'Slovo „práve" a tvar „píšem" vyjadrujú prítomný čas.',
  },
  {
    id: 'ps1-20',
    subject: 'slovencina',
    topic: 'Druhy viet',
    prompt: 'Aký je druh vety: „Kedy prídeš domov?"',
    type: 'choice',
    choices: [
      { id: 'a', text: 'oznamovacia' },
      { id: 'b', text: 'opytovacia' },
      { id: 'c', text: 'rozkazovacia' },
      { id: 'd', text: 'želacia' },
    ],
    answer: 'b',
    explanation: 'Veta sa pýta a končí sa otáznikom – je opytovacia.',
  },
  {
    id: 'ps1-21',
    subject: 'slovencina',
    topic: 'Druhy viet',
    prompt: 'Aký je druh vety: „Kiežby už boli prázdniny!"',
    type: 'choice',
    choices: [
      { id: 'a', text: 'oznamovacia' },
      { id: 'b', text: 'opytovacia' },
      { id: 'c', text: 'rozkazovacia' },
      { id: 'd', text: 'želacia' },
    ],
    answer: 'd',
    explanation: 'Veta vyjadruje želanie (slovo „kiežby") – je želacia.',
  },
  {
    id: 'ps1-22',
    subject: 'slovencina',
    topic: 'Druhy viet',
    prompt: 'Aký je druh vety: „Aké krásne počasie máme dnes!"',
    type: 'choice',
    choices: [
      { id: 'a', text: 'oznamovacia' },
      { id: 'b', text: 'opytovacia' },
      { id: 'c', text: 'rozkazovacia' },
      { id: 'd', text: 'zvolacia' },
    ],
    answer: 'd',
    explanation: 'Veta vyjadruje silný cit a končí sa výkričníkom – je zvolacia.',
  },
  {
    id: 'ps1-23',
    subject: 'slovencina',
    topic: 'Pravopis – veľké písmená',
    prompt: 'Ktorý zápis je správny?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'rieka dunaj' },
      { id: 'b', text: 'Rieka Dunaj' },
      { id: 'c', text: 'rieka Dunaj' },
      { id: 'd', text: 'Rieka dunaj' },
    ],
    answer: 'c',
    explanation: 'Slovo „rieka" je všeobecné podstatné meno (malé r), ale vlastný názov „Dunaj" sa píše s veľkým D.',
  },
  {
    id: 'ps1-24',
    subject: 'slovencina',
    topic: 'Pravopis – veľké písmená',
    prompt: 'Ktorá veta je napísaná správne?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'Moja sestra Mária býva v košiciach.' },
      { id: 'b', text: 'Moja sestra mária býva v Košiciach.' },
      { id: 'c', text: 'Moja sestra Mária býva v Košiciach.' },
      { id: 'd', text: 'moja sestra mária býva v košiciach.' },
    ],
    answer: 'c',
    explanation: 'Vlastné meno „Mária" aj názov mesta „Košice" sa píšu s veľkým začiatočným písmenom.',
  },
  {
    id: 'ps1-25',
    subject: 'slovencina',
    topic: 'Pravopis – dvojhlásky',
    prompt: 'Ktoré slovo obsahuje dvojhlásku „ô"?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'kôň' },
      { id: 'b', text: 'kočka' },
      { id: 'c', text: 'koleno' },
      { id: 'd', text: 'kút' },
    ],
    answer: 'a',
    explanation: '„Kôň" obsahuje dvojhlásku ô (číta sa „uo").',
  },
  {
    id: 'ps1-26',
    subject: 'slovencina',
    topic: 'Pravopis – dvojhlásky',
    prompt: 'Ktoré slovo obsahuje dvojhlásku „iu"?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'cudziu' },
      { id: 'b', text: 'mama' },
      { id: 'c', text: 'pero' },
      { id: 'd', text: 'kniha' },
    ],
    answer: 'a',
    explanation: 'V slove „cudziu" je dvojhláska „iu" (napr. v 4. páde – cudziu vec).',
  },
  {
    id: 'ps1-27',
    subject: 'slovencina',
    topic: 'Pravopis – ä',
    prompt: 'Ktoré slovo sa píše s ä?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'm_kký' },
      { id: 'b', text: 'mesto' },
      { id: 'c', text: 'med' },
      { id: 'd', text: 'metla' },
    ],
    answer: 'a',
    explanation: '„Mäkký" sa píše s ä – po spoluhláske m.',
  },
  {
    id: 'ps1-28',
    subject: 'slovencina',
    topic: 'Synonymá',
    prompt: 'Vyber synonymum k slovu „krásny":',
    type: 'choice',
    choices: [
      { id: 'a', text: 'škaredý' },
      { id: 'b', text: 'pekný' },
      { id: 'c', text: 'malý' },
      { id: 'd', text: 'starý' },
    ],
    answer: 'b',
    explanation: '„Krásny" a „pekný" majú podobný význam – sú to synonymá.',
  },
  {
    id: 'ps1-29',
    subject: 'slovencina',
    topic: 'Synonymá',
    prompt: 'Vyber synonymum k slovu „rýchlo":',
    type: 'choice',
    choices: [
      { id: 'a', text: 'pomaly' },
      { id: 'b', text: 'svižne' },
      { id: 'c', text: 'ticho' },
      { id: 'd', text: 'hlučne' },
    ],
    answer: 'b',
    explanation: '„Rýchlo" a „svižne" znamenajú približne to isté.',
  },
  {
    id: 'ps1-30',
    subject: 'slovencina',
    topic: 'Antonymá',
    prompt: 'Aké je antonymum slova „veľký"?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'obrovský' },
      { id: 'b', text: 'malý' },
      { id: 'c', text: 'široký' },
      { id: 'd', text: 'vysoký' },
    ],
    answer: 'b',
    explanation: 'Opakom slova „veľký" je „malý".',
  },
  {
    id: 'ps1-31',
    subject: 'slovencina',
    topic: 'Antonymá',
    prompt: 'Aké je antonymum slova „začiatok"?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'stred' },
      { id: 'b', text: 'koniec' },
      { id: 'c', text: 'pokračovanie' },
      { id: 'd', text: 'úvod' },
    ],
    answer: 'b',
    explanation: 'Opakom „začiatku" je „koniec".',
  },
  {
    id: 'ps1-32',
    subject: 'slovencina',
    topic: 'Predložky',
    prompt: 'Doplň správnu predložku: „Idem ___ kamarátovi."',
    type: 'choice',
    choices: [
      { id: 'a', text: 'k' },
      { id: 'b', text: 'ku' },
      { id: 'c', text: 's' },
      { id: 'd', text: 'so' },
    ],
    answer: 'a',
    explanation: 'Pred slovom „kamarátovi" (začína na k, ale nie na k+spoluhláska problémovú) používame „k". „Ku" sa používa pred slovami začínajúcimi na k alebo g (napr. ku knihe).',
  },
  {
    id: 'ps1-33',
    subject: 'slovencina',
    topic: 'Predložky',
    prompt: 'Doplň správnu predložku: „Hrám sa ___ sestrou."',
    type: 'choice',
    choices: [
      { id: 'a', text: 's' },
      { id: 'b', text: 'so' },
      { id: 'c', text: 'z' },
      { id: 'd', text: 'zo' },
    ],
    answer: 'b',
    explanation: 'Pred slovom začínajúcim na s/š/z/ž používame „so" (so sestrou).',
  },
  {
    id: 'ps1-34',
    subject: 'slovencina',
    topic: 'Predložky',
    prompt: 'Doplň správnu predložku: „Vybral som knihu ___ police."',
    type: 'choice',
    choices: [
      { id: 'a', text: 's' },
      { id: 'b', text: 'so' },
      { id: 'c', text: 'z' },
      { id: 'd', text: 'zo' },
    ],
    answer: 'c',
    explanation: 'Pohyb „odkiaľ" – z police. „Zo" by sme použili pred slovami na s/š/z/ž (napr. zo školy).',
  },
  {
    id: 'ps1-35',
    subject: 'slovencina',
    topic: 'Predložky',
    prompt: 'Doplň správnu predložku: „Sedím ___ izbe."',
    type: 'choice',
    choices: [
      { id: 'a', text: 'v' },
      { id: 'b', text: 'vo' },
      { id: 'c', text: 'z' },
      { id: 'd', text: 'na' },
    ],
    answer: 'a',
    explanation: '„V izbe" – pred slovom začínajúcim na samohlásku alebo bežnú spoluhlásku používame „v". „Vo" by bolo pred v/f (vo vode).',
  },
  {
    id: 'ps1-36',
    subject: 'slovencina',
    topic: 'Pravopis – y/i v koncovkách',
    prompt: 'Doplň správne y/i: „Chlapc_ sa hrali na dvore."',
    type: 'choice',
    choices: [
      { id: 'a', text: 'Chlapci' },
      { id: 'b', text: 'Chlapcy' },
    ],
    answer: 'a',
    explanation: 'V množnom čísle životných podstatných mien mužského rodu (vzor chlap) sa píše mäkké i: chlapci.',
  },
  {
    id: 'ps1-37',
    subject: 'slovencina',
    topic: 'Pravopis – ie/é',
    prompt: 'Ktoré slovo je napísané správne?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'mlieko' },
      { id: 'b', text: 'mléko' },
      { id: 'c', text: 'mliéko' },
    ],
    answer: 'a',
    explanation: 'V slove „mlieko" je dvojhláska „ie".',
  },
  {
    id: 'ps1-38',
    subject: 'slovencina',
    topic: 'Slovné druhy – číslovky',
    prompt: 'Ktoré slovo je základná číslovka?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'tretí' },
      { id: 'b', text: 'tri' },
      { id: 'c', text: 'trojitý' },
      { id: 'd', text: 'trikrát' },
    ],
    answer: 'b',
    explanation: '„Tri" je základná číslovka – odpovedá na otázku „koľko?".',
  },
  {
    id: 'ps1-39',
    subject: 'slovencina',
    topic: 'Skladba vety – prívlastok',
    prompt: 'Ktoré slovo je prívlastkom vo vete: „Vysoký strom rastie pri ceste."?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'vysoký' },
      { id: 'b', text: 'strom' },
      { id: 'c', text: 'rastie' },
      { id: 'd', text: 'pri ceste' },
    ],
    answer: 'a',
    explanation: 'Prívlastok bližšie určuje podstatné meno – „vysoký" určuje strom.',
  },
  {
    id: 'ps1-40',
    subject: 'slovencina',
    topic: 'Časy slovies – tvar',
    prompt: 'Ktorý tvar slovesa „písať" je v budúcom čase?',
    type: 'choice',
    choices: [
      { id: 'a', text: 'písal som' },
      { id: 'b', text: 'píšem' },
      { id: 'c', text: 'budem písať' },
      { id: 'd', text: 'napísaný' },
    ],
    answer: 'c',
    explanation: 'Tvar „budem písať" vyjadruje budúci čas (zložený tvar).',
  },
];
